Milestones_3
eosnetworkfoundation/grant-milestones pull request #111
Opened 2023-07-20 04:08 UTC by chenminmin4

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/XXX < please fill this in with the PR number of your application.

2023-08-09 14:26 UTC, wanderingbort approved these changes

2023-08-09 14:26 UTC, wanderingbort commented on deliveries/EVMNS_milestone_3.MD
> +| 4  | Domain Management System           | [Management System](http://13.231.106.101:8098/)                                                   | Build EVMNS domain management system to realize admini
This link is dead for me.  I know we took some time to review but this will be recorded in the repository for historical purposes.  If there is a more durable link to the domain management system ( even if the test user/password no longer works) , please update it here.

2023-08-09 14:43 UTC, ericpassmore requested changes
45 failing tests 

  1) Contract: EVMRegistrarController
       should permit new registrations:

      AssertionError: expected +0 to equal 31536000
      + expected - actual

      -0
      +31536000
      
      at Context.<anonymous> (test/evmregistrar/TestEVMRegistrarController.js:218:10)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at listOnTimeout (node:internal/timers:540:9)
      at processTimers (node:internal/timers:514:7)

  2) Contract: EVMRegistrarController
       should permit new registrations with resolver and records:

      AssertionError: expected +0 to equal 31536000
      + expected - actual

      -0
      +31536000
      
      at Context.<anonymous> (test/evmregistrar/TestEVMRegistrarController.js:278:10)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at listOnTimeout (node:internal/timers:540:9)
      at processTimers (node:internal/timers:514:7)

  3) Contract: EVMRegistrarController
       should permit a registration with resolver but no records:

      AssertionError: expected +0 to equal 31536000
      + expected - actual

      -0
      +31536000
      
      at Context.<anonymous> (test/evmregistrar/TestEVMRegistrarController.js:518:10)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at listOnTimeout (node:internal/timers:540:9)
      at processTimers (node:internal/timers:514:7)

  4) Name Wrapper
       like an ERC1155
         balanceOf
           when accounts don't own tokens
             returns zero for given addresses:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  5) Name Wrapper
       like an ERC1155
         balanceOf
           when accounts own some tokens
             returns the amount of tokens owned by the given addresses:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  6) Name Wrapper
       like an ERC1155
         balanceOfBatch
           when accounts don't own tokens
             returns zeros for each account:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  7) Name Wrapper
       like an ERC1155
         balanceOfBatch
           when accounts own some tokens
             returns amounts owned by each account in order passed:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  8) Name Wrapper
       like an ERC1155
         balanceOfBatch
           when accounts own some tokens
             returns multiple times the balance of the same address when asked:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  9) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when called by the multiTokenHolder
             debits transferred balance from sender:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  10) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when called by the multiTokenHolder
             credits transferred balance to receiver:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  11) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when called by the multiTokenHolder
             preserves existing balances which are not transferred by multiTokenHolder:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  12) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when called by an operator on behalf of the multiTokenHolder
             when operator is approved by multiTokenHolder
               debits transferred balance from sender:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  13) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when called by an operator on behalf of the multiTokenHolder
             when operator is approved by multiTokenHolder
               credits transferred balance to receiver:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  14) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when called by an operator on behalf of the multiTokenHolder
             when operator is approved by multiTokenHolder
               preserves operator's balances not involved in the transfer:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  15) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when sending to a valid receiver
             without data
               debits transferred balance from sender:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  16) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when sending to a valid receiver
             without data
               credits transferred balance to receiver:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  17) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when sending to a valid receiver
             with data
               debits transferred balance from sender:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  18) Name Wrapper
       like an ERC1155
         safeTransferFrom
           when sending to a valid receiver
             with data
               credits transferred balance to receiver:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  19) Name Wrapper
       like an ERC1155
         safeBatchTransferFrom
           when called by the multiTokenHolder
             debits transferred balances from sender:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  20) Name Wrapper
       like an ERC1155
         safeBatchTransferFrom
           when called by the multiTokenHolder
             credits transferred balances to receiver:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  21) Name Wrapper
       like an ERC1155
         safeBatchTransferFrom
           when called by an operator on behalf of the multiTokenHolder
             when operator is approved by multiTokenHolder
               debits transferred balances from sender:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  22) Name Wrapper
       like an ERC1155
         safeBatchTransferFrom
           when called by an operator on behalf of the multiTokenHolder
             when operator is approved by multiTokenHolder
               credits transferred balances to receiver:
     AssertionError: expected BigNumber{ _hex: '0x01', …(1) } to be an instance of BN or string
  

  23) Name Wrapper
       like an ERC1155
         safeBatchTransferFrom
           when called by an operator on behalf of the multiTokenHolder
             when operator is approved by multiTokenHolder
               preserves operator's balances not involved in the transfer:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  

  24) Name Wrapper
       like an ERC1155
         safeBatchTransferFrom
           when sending to a valid receiver
             without data
               debits transferred balances from sender:
     AssertionError: expected BigNumber{ _hex: '0x00', …(1) } to be an instance of BN or string
  [...]

2023-08-09 14:58 UTC, nsjames commented
I'm getting the same failing tests as @ericpassmore 

Additionally I also get this when doing `yarn hardhat node`

```
deploying "EVMNSRegistry" (tx: 0x2acc7592eee881aca93870e6617b5cc40107e587953aafe75d81d73268244497)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 643637 gas
deploying "RSASHA1Algorithm" (tx: 0x1ddd12b466c096fbc7c7aa30fcbdc398b14c0cc2519128c92867261e4f31a2bd)...: deployed at 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512 with 695194 gas
deploying "RSASHA256Algorithm" (tx: 0xb1d03cd93071e68ebe773183f2558221c74c443260f8108293eb85b678a90005)...: deployed at 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0 with 448967 gas
deploying "P256SHA256Algorithm" (tx: 0xc844df482f71470d977fd0fb9bf5eb1d78c23aa686e6e49e7a074c1c834a8a45)...: deployed at 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9 with 896222 gas
deploying "DummyAlgorithm" (tx: 0x02fc5bb95aa6f9fc19129b7b7bebe1a5b0c51a08205ccf62b1b6f1af84036679)...: deployed at 0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9 with 134217 gas
deploying "SHA1Digest" (tx: 0xdac2f3364f49e1472fd169fd600860a8d4e906ef615c481faef5053e5b52d681)...: deployed at 0x5FC8d32690cc91D4c39d9d3abcBD16989F875707 with 459448 gas
deploying "SHA256Digest" (tx: 0x01cea2225f9458fba18d6c04eb971d4ac46ca23774ec883d557fb8a3bd0e4846)...: deployed at 0x0165878A594ca255338adfa4d48449f69242Eb8F with 211298 gas
deploying "DummyDigest" (tx: 0xfc71d5e742e71d080167862bb84c78b77bc23c1a888bdae6fd9c29a17d898665)...: deployed at 0xa513E6E4b8f2a923D98304ec87F64353C4D5C853 with 123877 gas
deploying "DNSSECImpl" (tx: 0x6c7b508091faa0aac1dad7ee6930b71911f01d26e15d64b88fe9cd06c80c3f0d)...: deployed at 0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6 with 1832871 gas
Waiting on 9 transactions setting DNSSEC parameters
deploying "OffchainDNSResolver" (tx: 0x8f326f6cb8d1be0f9d090f85b0c5b5bad5e0df919e3cddbfc63448b23adb99f7)...: deployed at 0x68B1D87F95878fE05B998F19b66F4baba5De1aed with 1504355 gas
Deployed OffchainDNSResolver to 0x68B1D87F95878fE05B998F19b66F4baba5De1aed
deploying "Root" (tx: 0x7d19f6cd8e9db10216afdfc023066ec7f6c0f082374ffa2e824946ef439199ee)...: deployed at 0x3Aa5ebB10DC797CAC828524e59A333d0A371443c with 506825 gas
Setting owner of root node to root contract (tx: 0xdbe6dd47e3719bfa600a3a9d0d4b19bd874fa4edd07f644059ddff85b74becfb)...
Transferring root ownership to final owner (tx: 0x70d9c190d671de8aecbddafa221d2c1bfbd9f6eaae9fe531e45f6bcde91d84e9)...
Setting final owner as controller on root contract (tx: 0x89ae939b1ab024c909027c211f10dc5c1b1b37dc356a675e9ca2af7d209b29ab)...
deploying "TLDPublicSuffixList" (tx: 0x59f442f98bed95b2e4fb6e8cb8fba9ebbc1253cf0fb4e14a22e706c55a859616)...: deployed at 0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44 with 166669 gas
deploying "DNSRegistrar" (tx: 0x24245b575e45696d5118b88256ff80e75f157757946c030937c81c470519b409)...: deployed at 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f with 1635282 gas
Deployed DNSRegistrar to 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
Set DNSRegistrar as controller of Root (0x1ede9d9390fb74d6a1fcdac6a79cc58e92343c3d5d19af0830c37298460cf284)
deploying "BaseRegistrarImplementation" (tx: 0x13e6071f7743e89c0b100f66e4c1ffaed2d6edc821a25e2880cb119550d3c32c)...: deployed at 0x7a2088a1bFc9d81c55368AE168C2C02570cB814F with 1878985 gas
Transferring ownership of registrar to owner (tx: 0x79cd1c5a5cf207bf2b63f987c489d70742099a545a439f2f54396e16cf169732)...
Setting owner of evm node to registrar on root (tx: 0xf35ad3fca3e708de62ad1f7d0346c872322fb169316468ff4837787c0608329f)...
deploying "DummyOracle" (tx: 0x8aa27b57b0e27561de0a4918a60e783973abe0620f6fc3429c13836cc180ce2f)...: deployed at 0x67d269191c92Caf3cD7723F116c85e6E9bf55933 with 237129 gas
Transferring owner of DummyOracle to owner:0x2c8aF87F2875283FdC136ccfF5b0DF4D45A65F39 (tx: 0xf4e46abbf44f4cc6c9286ac3e3cabffddff1ca9f6c59a363182a814ae98e9bcd)...
deploying "ExponentialPremiumPriceOracle" (tx: 0x1c85d37d1326854ae0f96160d44d688bdba2ae260d218d1926859640b6edb8f4)...: deployed at 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690 with 959927 gas
deploying "StaticMetadataService" (tx: 0xce86e17694b84dd80d8af2685f1bba974a100491b83e33e0c0510d531981ad6d)...: deployed at 0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB with 233826 gas
deploying "ReverseRegistrar" (tx: 0xef6de0a64f27cf67afc8d2a571c615e0d6de5db9e84fec5f2d8931beb36af3e9)...: deployed at 0x9E545E3C0baAB3E08CdfD552C960A1050f373042 with 818305 gas
Setting owner of .reverse to owner on root (tx: 0x655a73e5b834c7105cba5cda77dd7ba46b35dd939197ac297298a4b027044aef)...
Setting owner of .addr.reverse to ReverseRegistrar on registry (tx: 0x49c1fa11dd726d0def7a861194006cef6121270655ac6ebf88d3d78580b59cd8)...
deploying "NameWrapper" (tx: 0x7839d13c3d3c5e7ef78b7c886f2e181826e96d8d05297a6d9d766be35d2c63b5)...: deployed at 0x851356ae760d987E095750cCeb3bC6014560891C with 5504012 gas
Adding NameWrapper as controller on registrar (tx: 0xaf775567e0e709ac962feb8356236b630661d1de5a6341258442cb6abc4c207d)...
No resolver set for .evm; not setting interface for NameWrapper
deploying "TestUnwrap" (tx: 0x45de4533b9feff1c1044789078adf7b77789f215ca17630c6c9ee6c2db5d851c)...: deployed at 0x95401dc811bb5740090279Ba06cfA8fcF6113778 with 970669 gas
No testnet wrappers found, skipping
deploying "EVMRegistrarController" (tx: 0x4eea85bb6087975d8fbcb1cc4f5fcf2931b9660ebee0c3f4375f62e6f5be8dff)...: deployed at 0x998abeb3E57409262aE5b751f60747921B33613E with 2172211 gas
WRAPPER OWNER 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Adding EVMRegistrarController as a controller of NameWrapper (tx: 0x9a8e345298788e6702231978f3acfbda331a81c1dda5ec2506c1097e2f6bfd78)...
Adding EVMRegistrarController as a controller of ReverseRegistrar (tx: 0x3f2d893202677cd099626628e74581cf7703a77c71c6fd25d56890943a5d80da)...
No resolver set for .eth; not setting interface for ETH Registrar Controller
deploying "StaticBulkRenewal" (tx: 0xcfc3c67e7142f9928d4015f8cbc21bd957a57d069aad250db84faa2c4128b8bd)...: deployed at 0x99bbA657f2BbC93c02D617f8bA121cB8Fc104Acf with 396872 gas
No resolver set for .evm; not setting interface for BulkRenewal
deploying "PublicResolver" (tx: 0x6516f02cce48857cd4dd48448d8f60495f90db6aa70513c4736d12933a186be5)...: deployed at 0x0E801D84Fa97b50751Dbf25036d067dCf18858bF with 2763920 gas
Setting default resolver on ReverseRegistrar to PublicResolver (tx: 0x02fb5f0a02408e735aab241606d1c6d6d2ae3903bc1f98ea9193957c924089aa)...
resolver.eth is not owned by the owner address, not setting resolver
Error HH604: Error running JSON-RPC server: ERROR processing E:\ENF\code\evmns-contracts2\deploy\utils\00_deploy_universal_resolver.ts:
Error: UniversalResolver: No batch gateway URLs provided
    at Object.func (E:\ENF\code\evmns-contracts2\deploy\utils\00_deploy_universal_resolver.ts:14:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)
    at processTimers (node:internal/timers:512:7)
    at async DeploymentsManager.executeDeployScripts (E:\ENF\code\evmns-contracts2\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1226:22)
    at async DeploymentsManager.runDeploy (E:\ENF\code\evmns-contracts2\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1059:5)
    at async SimpleTaskDefinition.action (E:\ENF\code\evmns-contracts2\node_modules\hardhat-deploy\src\index.ts:438:5)
    at async Environment._runTaskDefinition (E:\ENF\code\evmns-contracts2\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at async Environment.run (E:\ENF\code\evmns-contracts2\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (E:\ENF\code\evmns-contracts2\node_modules\hardhat-deploy\src\index.ts:584:32)
    at async Environment._runTaskDefinition (E:\ENF\code\evmns-contracts2\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at async Environment.run (E:\ENF\code\evmns-contracts2\node_modu [...]

2023-08-10 06:45 UTC, hdavis1988 commented on deliveries/EVMNS_milestone_3.MD
> +| 4  | Domain Management System           | [Management System](http://13.231.106.101:8098/)                                                   | Build EVMNS domain management system to realize admini
The link (http://13.231.106.101:8098/) has been restored and can be accessed normally. The account and password remain unchanged. 

Due to recent server upgrades, there have been unintended effects on the access to the management system. Apologize for causing you trouble. Thank you very much for your understanding.

2023-08-10 07:23 UTC, hdavis1988 commented
> 45 failing tests
> 
> 1. Contract: EVMRegistrarController
>    should permit new registrations:
>    AssertionError: expected +0 to equal 31536000
>  ...

Hi Eric,

We apologize for the inconvenience caused by the delay in the testing progress, which resulted in the incomplete alignment of the automated testing scripts with the actual requirements of the smart contracts. 

We will promptly improve the testing scripts and test cases and submit them in their entirety by Milestone 4. 

Furthermore, we have conducted multiple rounds of manual testing, and the correctness of all functionalities has been verified. 

Therefore, we kindly request for your understanding to temporarily overlook the issues with the automated testing scripts. 

Thank you very much!

2023-08-10 07:36 UTC, hdavis1988 commented
> Additionally I also get this when doing `yarn hardhat node`
> 
> Is the [README here](https://github.com/evmns/EVMNS) old?
> I don't see that command on the [contracts README](https://github.com/evmns/evmns-contracts/tree/main)

Hi James,

Regarding this issue, it appears that the BATCH_GATEWAY_URLS in your .env file is not configured correctly. Hence, please try renaming the ".env.org" in the root directory to ".env". 

Additionally, we have also updated the configuration instructions in the Readme file. 

Thank you very much!

2023-08-12 02:32 UTC, DenisCarriere approved these changes
Management System URL is still not working:
http://13.231.106.101:8098

Please setup a temporary DNS for testing purposes or have a static IP attached to the server.

Other then that, looks good on my side

2023-08-12 09:42 UTC, hdavis1988 commented
> Management System URL is still not working: http://13.231.106.101:8098
> 
> Please setup a temporary DNS for testing purposes or have a static IP attached to the server.
> 
> Other then that, looks good on my side

Oops! The same issue has occurred again, it's quite embarrassing!😅

The URL for the management system has been changed to http://35.78.173.243:8098/ and is now running smoothly.

Thank you for your patience!

2023-08-16 18:38 UTC, nsjames approved these changes

2023-08-17 08:07 UTC, hdavis1988 commented
> 45 failing tests
> 
> 1. Contract: EVMRegistrarController
>    should permit new registrations:
>    AssertionError: expected +0 to equal 31536000
>    ...
 
 @ericpassmore @nsjames

We are pleased to update both of you on the latest progress. 

The complete automated testing script and test cases have been finished and updated. Please verify again. 

Thank you very much!

2023-08-17 18:30 UTC, ericpassmore commented
Hmm, I'm still getting test failures. Here are my steps. Please take a look and let me know what changes I should make. 
1) `git pull origin main`
2) `yarn install`
3) `yarn test` 

yarn version 1.22.19
node v20.5.0
Running MacOS Intel 

`Yarn build` has the follow errors:
     1  hardhat.config.ts:109
     1  node_modules/@ethereum-waffle/chai/dist/esm/types.d.ts:2
     1  node_modules/@nomiclabs/hardhat-waffle/dist/src/type-extensions.d.ts:2

2023-08-17 19:58 UTC, ericpassmore commented
> Hmm, I'm still getting test failures. Here are my steps. Please take a look and let me know what changes I should make.
> 
> 1. `git pull origin main`
> 2. `yarn install`
> 3. `yarn test`
> 
> yarn version 1.22.19 node v20.5.0 Running MacOS Intel
> 
> `Yarn build` has the follow errors: 1 hardhat.config.ts:109 1 node_modules/@ethereum-waffle/chai/dist/esm/types.d.ts:2 1 node_modules/@nomiclabs/hardhat-waffle/dist/src/type-extensions.d.ts:2

Switched to node 18.9.1 Much better only two failures related to DNS
 1) Contract: OffchainDNSResolver
       should respond to resolution requests with a CCIP read request to the DNS gateway:
     AssertionError: Expected transaction to be reverted with OffchainLookup("0x4bf010f1b9beDA5450a8dD702ED602A104ff65EE", ["https://localhost:8000/query"], 
  
  2) Contract: OffchainDNSResolver
       rejects calls to resolveCallback() with an invalid TXT record:

2023-08-17 20:43 UTC, ericpassmore approved these changes

2023-08-18 09:54 UTC, hdavis1988 commented
> Switched to node 18.9.1 Much better only two failures related to DNS
> 
> 1. Contract: OffchainDNSResolver
>    should respond to resolution requests with a CCIP read request to the DNS gateway:
>    AssertionError: Expected transaction to be reverted with OffchainLookup("0x4bf010f1b9beDA5450a8dD702ED602A104ff65EE", ["https://localhost:8000/query"],
> 2. Contract: OffchainDNSResolver
>    rejects calls to resolveCallback() with an invalid TXT record:

 You can try the following steps:

1. Delete the following folders in the root directory: "artifacts", "build", "cache", "deployments", and "node_modules".
2. Configure the .env file with BATCH_GATEWAY_URLS=["https://api-testnet2.trust.one"].
3. Execute "yarn install" and "yarn test" again.

If the issue still persists, can further try switching to node 16.20.0

Please feel free to let us know if it still does not succeed.

Thank you for your patience! 😀

2023-08-18 13:48 UTC, BenjaminGormanPMP commented
Hi @chenminmin4 , can you confirm submittal for Milestone 3 invoice? Here is the template form for your review (https://docs.google.com/forms/d/e/1FAIpQLScxOkuWso5dJsQjCeOftGYNQrA2cdlkrKNB7B0piaTcBRwV9A/viewform).

2023-08-18 13:49 UTC, hdavis1988 commented
Hello everyone, please ignore the three additional commits added by chenminmin4 above, as they are unrelated to Milestone 3.

2023-08-18 13:50 UTC, BenjaminGormanPMP commented
> Hi @chenminmin4 , can you confirm submittal for Milestone 3 invoice? Here is the template form for your review (https://docs.google.com/forms/d/e/1FAIpQLScxOkuWso5dJsQjCeOftGYNQrA2cdlkrKNB7B0piaTcBRwV9A/viewform).

Hi @hdavis1988  , can you confirm submittal for Milestone 3 invoice? Here is the template form for your review (https://docs.google.com/forms/d/e/1FAIpQLScxOkuWso5dJsQjCeOftGYNQrA2cdlkrKNB7B0piaTcBRwV9A/viewform).

2023-08-18 14:25 UTC, hdavis1988 commented
> Hi @hdavis1988 , can you confirm submittal for Milestone 3 invoice? Here is the template form for your review (https://docs.google.com/forms/d/e/1FAIpQLScxOkuWso5dJsQjCeOftGYNQrA2cdlkrKNB7B0piaTcBRwV9A/viewform).

Hi Benjamin, the form has been submitted. Please check and confirm. 

Thank you very much!

2023-08-18 14:30 UTC, merged