Neutroswap Milestone 3
eosnetworkfoundation/grant-milestones pull request #164
Opened 2024-01-30 10:35 UTC by jonassunandar

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/222 < please fill this in with the PR number of your application.

2024-02-14 11:03 UTC, nsjames commented
I think there might be an error with the `.md` file here. It says it's for milestones 1 and 2, but this PR is for milestone 3. 

I also don't see the required deliverables listed there (the ones specified [here](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/tokenomics_enhancement_neutroswap.md#milestone-3---mainnet-deployment--marketing))

2024-02-14 13:19 UTC, jonassunandar commented
Hi @nsjames 
Sorry for pushing the wrong milestone 1 `.md`. Now it should be only for milestone 3

2024-02-19 14:12 UTC, wanderingbort requested changes

2024-02-19 14:12 UTC, wanderingbort commented on .DS_Store
please remove this file from the PR

2024-02-19 14:12 UTC, wanderingbort commented on deliveries/tokenomics_enhancement_neutroswap_milestone_3.md
> +| 3.    | Graph Node Deployment	 | [Graph Index & Query Node](https://dbi.foundation/) | We've published a private graph-node instance for the EOS-EVM mainnet environment. |
This link produces a 404 which I assume is due to it being "private" If that is intentional we can remove the link as the subgraph link below works just fine.

2024-02-19 15:41 UTC, jonassunandar commented on deliveries/tokenomics_enhancement_neutroswap_milestone_3.md
> +| 3.    | Graph Node Deployment	 | [Graph Index & Query Node](https://dbi.foundation/) | We've published a private graph-node instance for the EOS-EVM mainnet environment. |
I've corrected the link to the subgraph query dashboard. My apologies for providing the incorrect link initially.

2024-02-19 15:42 UTC, jonassunandar commented on .DS_Store
I've removed the .DS_Store file

2024-02-22 11:39 UTC, nsjames commented
Looks good. Swapped 1 EOS to USDT and it worked well (though with a lot of slippage)

2024-02-22 11:40 UTC, nsjames approved these changes

2024-03-04 10:30 UTC, jonassunandar reviewed
resolved broken link changes and removed .DS_STORE

2024-03-27 13:45 UTC, jonassunandar commented
Hi @wanderingbort do you have any other question regarding the milestone? I'd love to fix it asap

2024-04-18 15:04 UTC, merged