Milestone 1
eosnetworkfoundation/grant-milestones pull request #26
Opened 2022-10-14 13:33 UTC by theblockstalk

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/57

2022-11-14 18:03 UTC, larryk85 requested changes

2022-11-14 18:03 UTC, larryk85 commented on deliveries/antelope-ssi-toolkit-1.md
> +| 1. | Environment setup | NA | We discussed and realized that a running Antelope was not needed, and adds extra burden on developers to be able to test. In milestone 2 we will be using programmed DI
Please elaborate on why this is no longer needed.  When we evaluate these milestones we also need to be able to test out or run any systems to see how they operate.  I would still like to see something here to document or script setting up an environment.

2022-11-24 17:03 UTC, theblockstalk commented on deliveries/antelope-ssi-toolkit-1.md
> +| 1. | Environment setup | NA | We discussed and realized that a running Antelope was not needed, and adds extra burden on developers to be able to test. In milestone 2 we will be using programmed DI
To test the verifiable credentials against different Antelope accounts, we need to be able to generate a correct DID Document for the account. We realise that we can use a mock DID Document to achieve this kind of test without needing to have to install and depend on running an Antelope node - this makes running unit tests easier and simpler for contributors and allows us to develop quicker.

You can already see how this is done in the upcoming work we are doing:
https://github.com/Tonomy-Foundation/Antelope-SSI-Toolkit/blob/master/test/util/mockResolver.ts#L23

As you can see, we are using the same code that To generate the DID Document as we would if we were to attach to an antelope node (imported from the `antelope-did-resolver` package). Because of this there is no issue that we will face because we do not connect to such a node.

2022-12-02 09:53 UTC, theblockstalk commented on deliveries/antelope-ssi-toolkit-1.md
> +| 1. | Environment setup | NA | We discussed and realized that a running Antelope was not needed, and adds extra burden on developers to be able to test. In milestone 2 we will be using programmed DI
video explanation
https://www.loom.com/share/60a2ac5d476d45ea8736332f4f32ed4c

2022-12-15 22:24 UTC, larryk85 approved these changes

2022-12-16 03:43 UTC, linh2931 approved these changes

2022-12-19 16:09 UTC, wanderingbort commented on deliveries/antelope-ssi-toolkit-1.md
> +| 1. | Environment setup | NA | We discussed and realized that a running Antelope was not needed, and adds extra burden on developers to be able to test. In milestone 2 we will be using programmed DI
@theblockstalk for future comments/responses please try to update the submitted document so that the response is included. The repo's static state should be enough to re-read and "re-approve" at least theoretically.

2022-12-19 16:14 UTC, wanderingbort requested changes
minor clarification requested, otherwise it all looks great.

2022-12-19 16:14 UTC, wanderingbort commented on deliveries/antelope-ssi-toolkit-1.md
> +| 3. | Implementation of W3C Vrifiable Condition | <https://github.com/Tonomy-Foundation/did-jwt> and <https://github.com/Tonomy-Foundation/did-jwt-vc> | The bulk of this work was done in the forked
I see the PR's in the forked repository as well as a new one to sync in upstream changes. Is there any effort to integrate the changes from your local fork into the upstream client or are they incompatible for some reason? 

The long term maintenance imposed by maintaining a fork is concerning. 

Please reflect the response to this in the document itself.  If discussion is required before committing to a statement in the document we can use the comments.

2022-12-20 16:19 UTC, theblockstalk commented on deliveries/antelope-ssi-toolkit-1.md
> +| 3. | Implementation of W3C Vrifiable Condition | <https://github.com/Tonomy-Foundation/did-jwt> and <https://github.com/Tonomy-Foundation/did-jwt-vc> | The bulk of this work was done in the forked
they are not incompatible but have quite some structural changes that the broader W3C communities need to accept. We would like to see this done, but it's also more resources than this grant provided, so not guaranteed.

We have been invited to present these changes to W3C CCG meeting on February 14. It's an open invite so anyone is welcome:
https://www.w3.org/groups/cg/credentials/calendar#card-80a1023e-569b-4714-8fab-d1b84f2c3478-20230214T120000

We are actively engaged with the SSI community to get this integrated. They have already accepted the "Condition Proof 2022" standard so they are acutely aware of the concept of what we are doing. They need to accept the implementation.

2023-01-03 21:58 UTC, arhag approved these changes

2023-01-05 18:06 UTC, wanderingbort approved these changes

2023-01-18 15:58 UTC, merged