Research report double check (#1)
eosnetworkfoundation/grant-milestones pull request #64
Opened 2023-03-08 06:38 UTC by psy2848048

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/XXX < please fill this in with the PR number of your application.

2023-04-03 18:21 UTC, 766C6164 requested changes

2023-04-03 18:21 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> + We believe that Rust CDT can be executed on EOSVM in spite of few constraints like value types in several instructions based on our analysis. Overall, EOSVM provides a feasible environment to execut
It would be really nice to come up with some sample source code/tests that will show execution is possible or not and demonstrate limitations to better understand gaps and how large they are if any

2023-04-03 18:21 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +### Case 3: Wasmer integration on Antelope Leap
This is very informative and very good information, however I have a feeling that we are deviating from outlined in grant application milestone description. I dont think there is enough appetite for Wasmer integration into Leap currently.

2023-04-03 18:21 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +- If there is a lack of resources to maintain the EOSVM, integrating with Wasmer would be an option.
I dont think there is a lack of resources and Wasmer integration is a priority, but definitely would be nice to understand some estimates

2023-04-03 18:21 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +- Development and Testing: USD 180K
Can you please provide more fine-grained breakdown of tasks / resources / hours. Simple gantt chart or similar would help a lot. Thank you!

2023-04-03 18:21 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +The timeline is approximately 3 months for development and 2 months for testing and documentation.
Can you please describe your testing processes / approaches / tools?

2023-04-03 18:21 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +In addition, we estimated **USD 40K / yr** for the repository maintenance. This budget would continue before the community’s active contribution, or technical follow-up for other maintenance entity.
Can you please elaborate what will be included in maintenance and which resources/capacity would be allocated to it?

2023-04-04 16:21 UTC, jhlee-young commented on deliveries/rust-antelope-cdt-1.md
> +- If there is a lack of resources to maintain the EOSVM, integrating with Wasmer would be an option.
what estimates do you mean? is it about assumptions of the reason for Wasmer integration necessity?

2023-04-11 14:48 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +- If there is a lack of resources to maintain the EOSVM, integrating with Wasmer would be an option.
I meant it would be nice to understand better value and costs/resources for a wasmer integration, but this is I believe is pretty much off-topic to the milestone deliverable and if desired, should be a separate proposal.

2023-04-18 07:07 UTC, jhlee-young commented on deliveries/rust-antelope-cdt-1.md
> +The timeline is approximately 3 months for development and 2 months for testing and documentation.
plz check this new commit [c9507bf](https://github.com/eosnetworkfoundation/grant-milestones/pull/64/commits/c9507bffbc9b0e97f57513a5917aceec1bf88383)

2023-04-18 07:07 UTC, jhlee-young commented on deliveries/rust-antelope-cdt-1.md
> +In addition, we estimated **USD 40K / yr** for the repository maintenance. This budget would continue before the community’s active contribution, or technical follow-up for other maintenance entity.
plz check this new commit [c9507bf](https://github.com/eosnetworkfoundation/grant-milestones/pull/64/commits/c9507bffbc9b0e97f57513a5917aceec1bf88383)

2023-04-18 07:10 UTC, jhlee-young commented on deliveries/rust-antelope-cdt-1.md
> + We believe that Rust CDT can be executed on EOSVM in spite of few constraints like value types in several instructions based on our analysis. Overall, EOSVM provides a feasible environment to execut
we've written the validation report for wasm spec separately here. please check the report link below
https://github.com/DELIGHT-LABS/cosmwasm/blob/main/eos-check/result.md

2023-04-18 07:13 UTC, jhlee-young commented on deliveries/rust-antelope-cdt-1.md
> + We believe that Rust CDT can be executed on EOSVM in spite of few constraints like value types in several instructions based on our analysis. Overall, EOSVM provides a feasible environment to execut
As mentioned in the report, running a cosmwasm-generated contract directly on EOSVM needs interface mapping and others, which are more than the research. I've described which tasks are required in detail in this proposal. let us know if there's some lack of information 🙏

2023-05-05 18:50 UTC, linh2931 reviewed
The milestone description in the original grant application specified:

1. EOSVM API analysis
Analyze the interacting APIs with EOSVM and estimate the job size of developing the interaction layer
2. Antelope code structure research
Check does the code need to be changed & where would need to be changed
3. Feasibility check
Implement a small PoC layer including with a couple of API interaction & triggering contract.
4. (OPTIONAL) Simulation with DEX contract
Try to simulate porting the Cosmwasm DEX contract on EOSVM

I have trouble to correlate this deliverable to the specified goals.

The original grant application talked much about wasmer but this report focuses on CosmWams. 

It is not clear how a CosmWasm-based contract looks alike for a corresponding C++ EOS contract. It would be more clear if you show a flow of contract code --> compile --> set code --> execution.

How are host functions going to be implemented? How are persistent contract tables going to be used and implemented?

2023-05-05 18:50 UTC, linh2931 commented on deliveries/rust-antelope-cdt-1.md
> + Our research concluded that Cosmwasm only supports imports defined in Cosmwasm VM and they consists of functions so it can be executed fully on EOSVM. The code line [(1)](#reference) represents the
(1)](#reference) and all other references do not work.

2023-05-05 18:50 UTC, linh2931 commented on deliveries/rust-antelope-cdt-1.md
> +- If there is a lack of resources to maintain the EOSVM, integrating with Wasmer would be an option.
We have already have EOS VM OC, JIT, and Interpreter. Not much value to have yet another VM type.

2023-05-23 17:21 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +### Case 3: Wasmer integration on Antelope Leap
This, as I mentioned in another comment, might be a subject for another proposal, if desired and should not probably belong here

2023-05-23 17:22 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +- Development and Testing: USD 180K
Thank you!

2023-05-23 17:23 UTC, 766C6164 commented on deliveries/rust-antelope-cdt-1.md
> +The timeline is approximately 3 months for development and 2 months for testing and documentation.
Thank you

2023-05-31 07:55 UTC, jhlee-young commented on deliveries/rust-antelope-cdt-1.md
> + Our research concluded that Cosmwasm only supports imports defined in Cosmwasm VM and they consists of functions so it can be executed fully on EOSVM. The code line [(1)](#reference) represents the
my apologies, it should've directed to the number in the last section named `Reference` in this file. the links are working correctly on markdown viewer. could you check them in that section if you don't mind?

2023-06-22 08:13 UTC, psy2848048 commented
> The milestone description in the original grant application specified:
> 
> 1. EOSVM API analysis
>    Analyze the interacting APIs with EOSVM and estimate the job size of developing the interaction layer
> 2. Antelope code structure research
>    Check does the code need to be changed & where would need to be changed
> 3. Feasibility check
>    Implement a small PoC layer including with a couple of API interaction & triggering contract.
> 4. (OPTIONAL) Simulation with DEX contract
>    Try to simulate porting the Cosmwasm DEX contract on EOSVM
> 
> I have trouble to correlate this deliverable to the specified goals.
> 
> The original grant application talked much about wasmer but this report focuses on CosmWams.
> 
> It is not clear how a CosmWasm-based contract looks alike for a corresponding C++ EOS contract. It would be more clear if you show a flow of contract code --> compile --> set code --> execution.
> 
> How are host functions going to be implemented? How are persistent contract tables going to be used and implemented?

- As mentioned, EOSVM & Wasmer are VM implementations used to run standard WASM. These WASM binaries can be run on all VMs, even if the binaries are developed from different SDKs.
- Cosmwasm is an implementation of Wasmer on Cosmos SDK.
- The reason why we referred to Cosmwasm and its SDK is that they are the best implementations among other projects with Wasmer.
- If the Cosmwasm-based contracts could run on EOSVM, it could significantly reduce the cost of work in the post-integration phase.
- Therefore, we thought that the right direction is to research the export functions of each contract SDK and how to call EOSVM & Wasmer from Antelope & Cosmwasm. Here is the research on these VM calling interfaces.
- And the functions and flow of Cosmwasm corresponding to `setcode` of Antelope are stated [[here](https://github.com/DELIGHT-LABS/grant-milestones/blob/feedback0508/deliveries/rust-antelope-cdt-1.md#flow-correspondence-with-antelope)](https://github.com/DELIGHT-LABS/grant-milestones/blob/feedback0508/deliveries/rust-antelope-cdt-1.md#flow-correspondence-with-antelope). Please check.

2023-07-26 14:55 UTC, linh2931 approved these changes

2023-07-26 16:15 UTC, ABurton22 commented
Invoice sent for Payment.

Amy Burton

2023-07-26 16:15 UTC, merged